name: testRigor E2E on OpenCart (localhost)

on:
  push:
    branches: [ "**" ]

jobs:
  e2e:
    runs-on: ubuntu-latest
    env:
      TESTRIGOR_SUITE_ID: ${{ vars.TESTRIGOR_SUITE_ID }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Start OpenCart using the repo's docker-compose
      - name: Start OpenCart (docker-compose)
        run: |
          docker compose -f docker-compose.yml up -d --remove-orphans
          docker compose ps

      # Detect which port is published and export LOCAL_BASE_URL for later steps
      - name: Detect OpenCart URL
        shell: bash
        run: |
          if curl -fsSI http://localhost >/dev/null; then
            echo "LOCAL_BASE_URL=http://localhost" >> "$GITHUB_ENV"
          elif curl -fsSI http://localhost:8080 >/dev/null; then
            echo "LOCAL_BASE_URL=http://localhost:8080" >> "$GITHUB_ENV"
          else
            echo "LOCAL_BASE_URL=http://localhost" >> "$GITHUB_ENV"
          fi

      - name: Wait for OpenCart to be reachable
        shell: bash
        run: |
          for i in {1..60}; do
            if curl -fsS -o /dev/null -L "$LOCAL_BASE_URL"; then
              echo "OpenCart is up at $LOCAL_BASE_URL"; exit 0
            fi
            echo "Waiting for OpenCart... ($i/60)"; sleep 5
          done
          echo "OpenCart failed to start in time" >&2; exit 1

      - name: Verify HTTP headers (sanity)
        run: curl -LI "$LOCAL_BASE_URL" || true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install testRigor CLI
        run: npm i -g testrigor-cli

      - name: Trigger testRigor suite against localhost
        env:
          TESTRIGOR_CI_TOKEN: ${{ secrets.TESTRIGOR_CI_TOKEN }}
        run: |
          testrigor test-suite run "$OPENCART_SUITE_ID" \
            --token "$TESTRIGOR_CI_TOKEN" \
            --localhost --url "$LOCAL_BASE_URL"
